import React from 'react';
import type { ReportData } from '@/lib/report-analyzer';
import { BrainCircuit } from 'lucide-react';
interface ReportPreviewProps {
  data: ReportData | null;
}
export const ReportPreview = React.forwardRef<HTMLDivElement, ReportPreviewProps>(({ data }, ref) => {
  if (!data) return null;
  const getProbabilityColor = (probValue: number) => {
    if (probValue === 0) return 'text-gray-500';
    const normalized = Math.max(0, (probValue - 1) / 4); // Normalize 1-5 scale to 0-1
    if (normalized < 0.4) return 'text-red-600';
    if (normalized < 0.7) return 'text-yellow-600';
    return 'text-green-600';
  };
  return (
    <div ref={ref} className="bg-white text-black p-12 font-sans" style={{ width: '210mm', minHeight: '297mm' }}>
      <header className="flex items-center justify-between pb-8 border-b border-gray-300">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">{data.title}</h1>
          <p className="text-sm text-gray-500">Generated on: {data.generatedDate}</p>
        </div>
        <div className="flex items-center gap-3 text-indigo-600">
          <BrainCircuit className="w-10 h-10" />
          <span className="text-2xl font-bold">Axon Collective</span>
        </div>
      </header>
      <main className="mt-8">
        <section className="mb-10">
          <h2 className="text-xl font-semibold border-b-2 border-indigo-200 pb-2 mb-4 text-gray-700">Executive Summary</h2>
          <p className="text-base text-gray-600 leading-relaxed">{data.summary}</p>
        </section>
        <section className="mb-10">
          <h2 className="text-xl font-semibold border-b-2 border-indigo-200 pb-2 mb-4 text-gray-700">Key High-Probability Outcomes</h2>
          <div className="space-y-3">
            {data.keyOutcomes.length > 0 ? (
              data.keyOutcomes.map((outcome, index) => (
                <div key={index} className="flex justify-between items-center p-3 bg-gray-50 rounded-lg">
                  <p className="font-medium text-gray-800">{outcome.label} <span className="text-sm text-gray-500">(Tier {outcome.tier})</span></p>
                  <p className={`font-bold text-lg ${getProbabilityColor(outcome.probability)}`}>{outcome.probability.toFixed(2)}</p>
                </div>
              ))
            ) : (
              <p className="text-gray-500 italic">No outcomes met the high-probability threshold.</p>
            )}
          </div>
        </section>
        <section>
          <h2 className="text-xl font-semibold border-b-2 border-indigo-200 pb-2 mb-4 text-gray-700">Likely Scenarios</h2>
          <div className="space-y-6">
            {data.scenarios.length > 0 ? (
              data.scenarios.map((scenario, index) => (
                <div key={index} className="p-4 border border-gray-200 rounded-lg bg-white">
                  <h3 className="font-semibold text-indigo-700 mb-2">Scenario {index + 1}: Leading to "{scenario.path[scenario.path.length - 1].label}"</h3>
                  <div className="flex items-center space-x-2 text-sm text-gray-600">
                    {scenario.path.map((step, stepIndex) => (
                      <React.Fragment key={stepIndex}>
                        <span className={`px-2 py-1 rounded ${step.tier === 0 ? 'bg-indigo-100 font-bold' : 'bg-gray-100'}`}>{step.label}</span>
                        {stepIndex < scenario.path.length - 1 && <span className="text-gray-400">&rarr;</span>}
                      </React.Fragment>
                    ))}
                  </div>
                  <p className="text-right mt-2 font-medium text-sm">Final Outcome Probability: <span className={`font-bold ${getProbabilityColor(scenario.finalOutcomeProbability)}`}>{scenario.finalOutcomeProbability.toFixed(2)}</span></p>
                </div>
              ))
            ) : (
              <p className="text-gray-500 italic">No likely scenarios could be constructed based on the voting data.</p>
            )}
          </div>
        </section>
      </main>
      <footer className="text-center text-xs text-gray-400 pt-8 mt-8 border-t border-gray-300">
        <p>Report generated by Axon Collective | Built with ❤️ at Cloudflare</p>
      </footer>
    </div>
  );
});